version: "3.8"

services:
  backend:
    image: labstation-backend:latest
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env.production
    networks:
      - labstation-network
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`labstation.dev`) && PathPrefix(`/api`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=letsencrypt"
        - "traefik.http.services.api.loadbalancer.server.port=5000"

  frontend:
    image: labstation-frontend:latest
    networks:
      - labstation-network
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`labstation.dev`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.services.dashboard.loadbalancer.server.port=80"

networks:
  labstation-network:
    driver: overlay
  traefik-public:
    external: true
