version: "3.8"

services:
  backend:
    build: ./server
    container_name: labstation-backend
    restart: unless-stopped
    env_file:
      - ./server/.env.production
    networks:
      - labstation-network
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: labstation-frontend
    restart: unless-stopped
    networks:
      - labstation-network
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: labstation-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: labstation_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bfeb5d8f45473d92e0cd51055c6fce19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - labstation-network

networks:
  labstation-network:
    driver: bridge

volumes:
  postgres_data:
